CREATE VIEW vw_agent_metrics_arg AS
SELECT
    tenant_id,
    sessionId,
    chatId,
    sessionCreationTime,
    -- Fecha y hora Argentina para sessionCreationTime
    CONVERT(DATE, SWITCHOFFSET(sessionCreationTime, '-03:00')) AS sessionCreationTime_arg_date,
    CONVERT(TIME, SWITCHOFFSET(sessionCreationTime, '-03:00')) AS sessionCreationTime_arg_time,
   avgAttendingTime,
    avgResponseTime,
    queue,
    agentName,
    agentId,
    typification,
    closedTime,
    -- Fecha y hora Argentina para closedTime
    CONVERT(DATE, SWITCHOFFSET(closedTime, '-03:00')) AS closedTime_arg_date,
    CONVERT(TIME, SWITCHOFFSET(closedTime, '-03:00')) AS closedTime_arg_time,
    openSessions,
    closedSessions,
    onHold,
    opResponseTime,
    operatorResponses,
    sessionTransferIn,
    sessionTransferOut,
    sessionTransferOutNoMessages,
    closedWithNoMessages,
    timeoutNoMessages,
    agentTimeout,
    userTimeout,
    fromQueueAsignToOpAssigned,
    fromSessionStartToOpFirstResponse,
    fromQueueAsignToOpFirstResponse,
    fromOpAssignedToOpFirstResponse,
    fromQueueAsignToSessionClosed,
    fromOpAssignationToSessionClosed,
    sessionTimeout,
    conversationLink
FROM agent_metrics