"""esquema inicial

Revision ID: f1b8258183bd
Revises: 
Create Date: 2026-06-11 15:07:37.554732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f1b8258183bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('entity', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.String(length=255), nullable=True),
    sa.Column('detail', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_log_tenant_created', 'audit_log', ['tenant_id', 'created_at'], unique=False)
    op.create_table('tenants',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('tenant_name', sa.String(length=255), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('agents',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('agent_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'agent_email')
    )
    op.create_table('chats',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('channel_id', sa.String(length=255), nullable=True),
    sa.Column('contact_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'chat_id')
    )
    op.create_table('etl_control',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('endpoint', sa.String(length=50), nullable=False),
    sa.Column('last_ts', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'endpoint')
    )
    op.create_table('etl_runs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='running', nullable=False),
    sa.Column('stats', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('running','ok','partial','failed')", name='ck_etl_runs_status'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_etl_runs_tenant_started', 'etl_runs', ['tenant_id', 'started_at'], unique=False)
    op.create_table('queues',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('queue', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'queue')
    )
    op.create_table('tenant_settings',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('botmaker_client_id', sa.String(length=255), nullable=True),
    sa.Column('botmaker_secret_id', sa.String(length=255), nullable=True),
    sa.Column('botmaker_token_enc', sa.Text(), nullable=True),
    sa.Column('botmaker_refresh_token_enc', sa.Text(), nullable=True),
    sa.Column('etl_schedule_cron', sa.String(length=100), nullable=True),
    sa.Column('etl_initial_ts', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('etl_window_days', sa.Integer(), nullable=True),
    sa.Column('is_etl_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('siniestros_queue', sa.String(length=255), nullable=True),
    sa.Column('siniestros_button', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_login_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("(role = 'superadmin' AND tenant_id IS NULL) OR (role <> 'superadmin' AND tenant_id IS NOT NULL)", name='ck_users_tenant_by_role'),
    sa.CheckConstraint("role IN ('superadmin','tenant_admin','viewer')", name='ck_users_role'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('agent_metrics',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=150), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=True),
    sa.Column('session_creation_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('avg_attending_time', sa.Integer(), nullable=True),
    sa.Column('avg_response_time', sa.Integer(), nullable=True),
    sa.Column('queue', sa.String(length=255), nullable=True),
    sa.Column('agent_name', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('typification', sa.String(length=255), nullable=True),
    sa.Column('closed_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('open_sessions', sa.Integer(), nullable=True),
    sa.Column('closed_sessions', sa.Integer(), nullable=True),
    sa.Column('on_hold', sa.Integer(), nullable=True),
    sa.Column('op_response_time', sa.Integer(), nullable=True),
    sa.Column('operator_responses', sa.Integer(), nullable=True),
    sa.Column('session_transfer_in', sa.Integer(), nullable=True),
    sa.Column('session_transfer_out', sa.Integer(), nullable=True),
    sa.Column('session_transfer_out_no_messages', sa.Integer(), nullable=True),
    sa.Column('closed_with_no_messages', sa.Integer(), nullable=True),
    sa.Column('timeout_no_messages', sa.Integer(), nullable=True),
    sa.Column('agent_timeout', sa.Integer(), nullable=True),
    sa.Column('user_timeout', sa.Integer(), nullable=True),
    sa.Column('from_queue_asign_to_op_assigned', sa.Integer(), nullable=True),
    sa.Column('from_session_start_to_op_first_response', sa.Integer(), nullable=True),
    sa.Column('from_queue_asign_to_op_first_response', sa.Integer(), nullable=True),
    sa.Column('from_op_assigned_to_op_first_response', sa.Integer(), nullable=True),
    sa.Column('from_queue_asign_to_session_closed', sa.Integer(), nullable=True),
    sa.Column('from_op_assignation_to_session_closed', sa.Integer(), nullable=True),
    sa.Column('session_timeout', sa.Integer(), nullable=True),
    sa.Column('conversation_link', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'queue'], ['queues.tenant_id', 'queues.queue'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'session_id')
    )
    op.create_index('ix_agent_metrics_tenant_chat', 'agent_metrics', ['tenant_id', 'chat_id'], unique=False)
    op.create_index('ix_agent_metrics_tenant_creation', 'agent_metrics', ['tenant_id', 'session_creation_time'], unique=False)
    op.create_table('agent_performance',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('performance_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('checkin', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('checkout', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_email'], ['agents.tenant_id', 'agents.agent_email'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'performance_id')
    )
    op.create_table('agent_performance_queues',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('agent_email', sa.String(length=255), nullable=False),
    sa.Column('queue', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'agent_email'], ['agents.tenant_id', 'agents.agent_email'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'queue'], ['queues.tenant_id', 'queues.queue'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'agent_email', 'queue')
    )
    op.create_table('backup_jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('type', sa.String(length=20), server_default='full', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('s3_key_result', sa.String(length=500), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_backup_jobs_status'),
    sa.CheckConstraint("type IN ('full','incremental')", name='ck_backup_jobs_type'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_backup_jobs_tenant_created', 'backup_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('chat_details',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('last_session_creation_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('whatsapp_window_close_datetime', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('queue_id', sa.String(length=255), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('on_hold_agent_id', sa.String(length=50), nullable=True),
    sa.Column('last_user_message_datetime', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('is_tester', sa.Boolean(), nullable=True),
    sa.Column('is_bot_muted', sa.Boolean(), nullable=True),
    sa.Column('is_banned', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'chat_id'], ['chats.tenant_id', 'chats.chat_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'chat_id')
    )
    op.create_table('chat_tags',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('tag', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'chat_id'], ['chats.tenant_id', 'chats.chat_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'chat_id', 'tag')
    )
    op.create_table('chat_variables',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('chat_id', sa.String(length=50), nullable=False),
    sa.Column('var_key', sa.String(length=100), nullable=False),
    sa.Column('var_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'chat_id'], ['chats.tenant_id', 'chats.chat_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'chat_id', 'var_key')
    )
    op.create_table('etl_stage_errors',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('run_id', sa.BigInteger(), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['etl_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('messages',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('creation_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('message_from', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('queue_id', sa.String(length=255), nullable=True),
    sa.Column('session_creation_time', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('chat_id', sa.String(length=50), nullable=True),
    sa.Column('session_id', sa.String(length=150), nullable=True),
    sa.Column('whatsapp_template_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'chat_id'], ['chats.tenant_id', 'chats.chat_id'], ),
    sa.ForeignKeyConstraint(['tenant_id', 'queue_id'], ['queues.tenant_id', 'queues.queue'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'id')
    )
    op.create_index('ix_messages_tenant_chat_time', 'messages', ['tenant_id', 'chat_id', 'creation_time'], unique=False)
    op.create_index('ix_messages_tenant_time', 'messages', ['tenant_id', 'creation_time'], unique=False)
    op.create_table('retry_jobs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('requested_by', sa.BigInteger(), nullable=True),
    sa.Column('filters', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('counts_before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('counts_after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('processed', sa.Integer(), nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('error_summary', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_retry_jobs_status'),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.tenant_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_retry_jobs_tenant_created', 'retry_jobs', ['tenant_id', 'created_at'], unique=False)
    op.create_table('encryption_params',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('config_id', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.String(length=50), nullable=True),
    sa.Column('encrypted_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id')
    )
    op.create_table('message_buttons',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('button', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id', 'button')
    )
    op.create_table('message_call',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('event', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id')
    )
    op.create_table('message_carouselitems',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('item_index', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('carousel_item', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id', 'item_index')
    )
    op.create_table('message_content',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('content_type', sa.String(length=50), nullable=True),
    sa.Column('text', sa.Text(), nullable=True),
    sa.Column('selected_button', sa.String(length=255), nullable=True),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('original_audio_url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id')
    )
    op.create_table('message_files',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('file_type', sa.String(length=20), nullable=False),
    sa.Column('original_url', sa.String(length=500), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=True),
    sa.Column('downloaded_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='ok', nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.CheckConstraint("status IN ('ok','forbidden','not_found','error','skipped')", name='ck_message_files_status'),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id', 'file_type')
    )
    op.create_index('ix_message_files_tenant_status_type', 'message_files', ['tenant_id', 'status', 'file_type'], unique=False)
    op.create_table('message_location',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('latitude', sa.String(length=50), nullable=True),
    sa.Column('longitude', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'message_id')
    )
    op.create_table('message_media',
    sa.Column('tenant_id', sa.String(length=50), nullable=False),
    sa.Column('media_id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('message_id', sa.String(length=50), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id', 'message_id'], ['messages.tenant_id', 'messages.id'], ),
    sa.PrimaryKeyConstraint('tenant_id', 'media_id')
    )
    op.create_index('ix_message_media_tenant_message', 'message_media', ['tenant_id', 'message_id'], unique=False)
    # ### end Alembic commands ###

    # Vista usada por los dashboards y el visor (reconstruida del .pbix legacy).
    # Una fila por mensaje × archivo (LEFT JOIN: mensajes sin archivo → file_* NULL).
    op.execute("""
        CREATE VIEW vw_chat_full_conversation AS
        SELECT
            m.tenant_id,
            m.chat_id,
            c.contact_id,
            m.session_id,
            m.session_creation_time,
            m.id            AS message_id,
            m.creation_time AS message_time,
            m.message_from,
            m.agent_id,
            m.queue_id,
            mc.content_type,
            mc.text         AS content_text,
            mc.selected_button AS content_selected_button,
            m.whatsapp_template_name,
            mf.file_type,
            mf.status       AS file_status,
            mf.s3_key
        FROM messages m
        LEFT JOIN chats c
               ON c.tenant_id = m.tenant_id AND c.chat_id = m.chat_id
        LEFT JOIN message_content mc
               ON mc.tenant_id = m.tenant_id AND mc.message_id = m.id
        LEFT JOIN message_files mf
               ON mf.tenant_id = m.tenant_id AND mf.message_id = m.id
    """)


def downgrade() -> None:
    op.execute("DROP VIEW IF EXISTS vw_chat_full_conversation")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_message_media_tenant_message', table_name='message_media')
    op.drop_table('message_media')
    op.drop_table('message_location')
    op.drop_index('ix_message_files_tenant_status_type', table_name='message_files')
    op.drop_table('message_files')
    op.drop_table('message_content')
    op.drop_table('message_carouselitems')
    op.drop_table('message_call')
    op.drop_table('message_buttons')
    op.drop_table('encryption_params')
    op.drop_index('ix_retry_jobs_tenant_created', table_name='retry_jobs')
    op.drop_table('retry_jobs')
    op.drop_index('ix_messages_tenant_time', table_name='messages')
    op.drop_index('ix_messages_tenant_chat_time', table_name='messages')
    op.drop_table('messages')
    op.drop_table('etl_stage_errors')
    op.drop_table('chat_variables')
    op.drop_table('chat_tags')
    op.drop_table('chat_details')
    op.drop_index('ix_backup_jobs_tenant_created', table_name='backup_jobs')
    op.drop_table('backup_jobs')
    op.drop_table('agent_performance_queues')
    op.drop_table('agent_performance')
    op.drop_index('ix_agent_metrics_tenant_creation', table_name='agent_metrics')
    op.drop_index('ix_agent_metrics_tenant_chat', table_name='agent_metrics')
    op.drop_table('agent_metrics')
    op.drop_table('users')
    op.drop_table('tenant_settings')
    op.drop_table('queues')
    op.drop_index('ix_etl_runs_tenant_started', table_name='etl_runs')
    op.drop_table('etl_runs')
    op.drop_table('etl_control')
    op.drop_table('chats')
    op.drop_table('agents')
    op.drop_table('tenants')
    op.drop_index('ix_audit_log_tenant_created', table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
